config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:edit, :new, :create, :update] do
    resources :messages, only: [:index, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.message? ? last_message.message : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader

  validates :message, presence: true, unless: :image_nil?

  private
    def image_nil?
      image.presence
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:%i(name))
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice:'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "グループを編集しました"
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages =@group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_messages = @messages.where('id > ?', params[:id]) }
    end
  end

  def create
    @message = @group.messages.new(message_params)

    if @message.save
      respond_to do |format|
        format.html
        format.json
      end
    else
      flash.now[:alert] = "メッセージもしくは画像を送信してください"
      render :index
    end

  end

  private

  def message_params
    params.require(:message).permit(:message, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:name]}%" ).where("id NOT IN (#{current_user.id})")

    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
    @user =User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: "chat-group-form__input", id: "chat_group_name", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      .chat-group-form__label チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: '追加したいユーザー名を入力してください', type: "text"}
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      .chat-group-form__label チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        - if controller.action_name == "edit"
          - @group.users.each do |user|
            .chat-group-user.clearfix
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}/
              %p.chat-group-user__name
                = user.name
        - else
          .chat-group-user.clearfix
            %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}/
            %p.chat-group-user__name
              = current_user.name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
= render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notification'
    = yield

app/views/messages/_message.html.haml
.chat-main__message.clearfix{"data-id": "#{message.id}"}
  .chat-main__message-name
    = message.user.name
  .chat-main__message-date
    = message.created_at.strftime("%Y/%m/%d %H:%M")
  .chat-main__message-body
  - if message.message.present?
    = message.message
  - if message.image.present?
    = image_tag message.image.url

app/views/messages/index.html.haml
= render 'shared/side_bar'

.chat-main
  .chat-main__header
    .chat-main__header--group.clearfix
      .chat-main__header--group-name
        = @group.name
      = link_to edit_group_path(@group), class: "chat-main__header--group-edit-btn" do
        Edit
    .chat-main__header-members
      %p Members: #{@group.users.pluck(:name).join(", ")}

  .chat-main__body
    .chat-main__message-list
      = render partial: 'message', collection: @messages

  .chat-main__footer
    = form_for [@group, @message], html: {class: 'chat-main__footer-form', id: 'new__message'} do |f|
      .chat-main__footer-body
        = f.text_field :message, class: 'chat-footer__body--message', placeholder: 'type a message'
        = f.label :image, class: 'chat-footer__body--chat-file' do
          = fa_icon 'picture-o', class: 'icon'
          = f.file_field :image, class: 'chat-footer__body--image'
        = f.submit 'Send', class: 'chat-footer__body--submit'

app/views/shared/_side_bar.html.haml
.chat-side
  .chat-side__user
    .chat-side__user-content
      .chat-side__user-name
        %p= current_user.name
      = link_to new_group_path, class: "chat-side__user--new-gruop" do
        %i.fa.fa-edit
      = link_to edit_user_path(current_user), class:"chat-side__user--option" do
        %i.fa.fa-cog

  .chat-side__groups
    .chat-side__groups-list
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .chat-side__group
            .chat-side__group-name
              = group.name
            .chat-side__group-message
              = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/example.html.erb
<div class='chat-main__footer'
  %form{class: "chat-main__footer-form"}
    .chat-main__footer-body
      %input{name: "message[body]", placeholder: "type a message", class: "chat-footer__body--message"}
      %label{class: "chat-footer__body--chat-file", for: "message-image"}
        %i.fa.fa-image
        %input{type: "file", class: "chat-footer__body--image", id: "message-image"}
    %input{type: "submit", value: "send", class: "chat-footer__body--submit"}